<?= $this->extend('Layout/Starter') ?>
<?= $this->section('content') ?>
<div class="container-fluid px-4 py-6">
    <section class="page-hero">
        <div class="hero-kicker">LOCATOR</div>
        <h1>SEARCH GRID</h1>
        <p>Find keys, licenses, operators, and live device binds.</p>
    </section>
    <div class="glass-card rounded-2xl p-6 mb-6">
        <form method="get" action="<?= site_url('search') ?>" class="hud-search scan-form">
            <span class="scan-line"></span>
            <input type="text" name="q" value="<?= esc($q) ?>" placeholder="SCAN KEY / OPERATOR / DEVICE">
            <button type="submit" class="submit">SCAN</button>
        </form>
    </div>
    <div class="grid grid-cols-1 gap-6">
        <div class="glass-card rounded-2xl p-6">
            <h2 class="mb-4">KEYS</h2>
            <?php if ($keys) : ?>
                <div class="scan-key-list">
                <?php foreach ($keys as $k) :
                    $info = getDevice($k['devices'] ?? '');
                    $used = $info->total > 0;
                    $statusOn = !empty($k['status']);
                    $expired = !empty($k['expired_date']);
                    $hours = (int) ($k['duration'] ?? 0);
                ?>
                    <article class="scan-key <?= $used ? 'is-used' : 'is-idle' ?>">
                        <header>
                            <span class="hud-chip"><?= $used ? 'USED' : 'UNUSED' ?></span>
                            <span class="hud-chip"><?= $statusOn ? 'ACTIVE' : 'INACTIVE' ?></span>
                            <strong class="scan-code"><?= esc($k['user_key']) ?></strong>
                        </header>
                        <div class="scan-op">GENERATED BY <b>@<?= esc($k['registrator'] ?: 'unknown') ?></b></div>
                        <div class="scan-meta">
                            <div><small>OPERATOR USERNAME</small><b><?= esc($k['registrator'] ?: '—') ?></b></div>
                            <div><small>GAME</small><b><?= esc($k['game'] ?: 'PUBG') ?></b></div>
                            <div><small>DURATION</small><b><?= $hours ?>h</b></div>
                            <div><small>DEVICES</small><b><?= (int) $info->total ?>/<?= (int) ($k['max_devices'] ?? 0) ?></b></div>
                            <div><small>EXPIRES</small><b><?= $expired ? esc($k['expired_date']) : 'NOT STARTED' ?></b></div>
                            <div><small>LAST PING</small><b><?= !empty($k['last_ping']) ? esc($k['last_ping']) : '—' ?></b></div>
                        </div>
                        <?php if ($used) : ?>
                        <div class="scan-used">
                            <small>BOUND DEVICES</small>
                            <code><?= esc(str_replace(["\n", "\r"], ' · ', $info->devices)) ?></code>
                        </div>
                        <?php else : ?>
                        <p class="muted">Key generated, no device bound yet.</p>
                        <?php endif; ?>
                        <a class="ghost-btn" href="<?= site_url('keys/' . $k['id_keys']) ?>">OPEN KEY</a>
                    </article>
                <?php endforeach; ?>
                </div>
            <?php else : ?>
                <p class="muted"><?= strlen($q) >= 2 ? 'No keys matched.' : 'Type at least 2 characters to scan.' ?></p>
            <?php endif; ?>
        </div>
        <div class="glass-card rounded-2xl p-6">
            <h2 class="mb-4">OPERATORS (KEY GENERATORS)</h2>
            <?php if ($users) : ?>
                <div class="overflow-x-auto">
                    <table class="w-full">
                        <thead><tr><th class="text-left px-3 py-2">Username</th><th class="text-left px-3 py-2">Fullname</th><th class="text-left px-3 py-2">Role</th></tr></thead>
                        <tbody>
                        <?php foreach ($users as $u) : ?>
                            <tr>
                                <td class="px-3 py-2"><b>@<?= esc($u['username']) ?></b></td>
                                <td class="px-3 py-2"><?= esc($u['fullname'] ?? '') ?></td>
                                <td class="px-3 py-2"><?= getLevel($u['level']) ?></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            <?php else : ?>
                <p class="muted">No operator username found for this scan.</p>
            <?php endif; ?>
        </div>
    </div>
</div>
<style>
.scan-key-list { display: grid; gap: 12px; }
.scan-key {
    border: 1px solid rgba(0,255,208,.22);
    background: rgba(4,12,24,.72);
    padding: 14px 16px;
    min-width: 0;
}
.scan-key.is-used { border-color: rgba(182,255,59,.35); }
.scan-key header { display: flex; flex-wrap: wrap; gap: 8px; align-items: center; margin-bottom: 10px; }
.scan-code { font-family: Orbitron, sans-serif; letter-spacing: .06em; word-break: break-all; }
.scan-op {
    margin: 0 0 12px;
    padding: 8px 10px;
    border: 1px solid rgba(0,255,208,.28);
    color: #00ffd0;
    font-family: Orbitron, sans-serif;
    letter-spacing: .12em;
    font-size: 12px;
}
.scan-op b { color: #b6ff3b; }
.scan-meta {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
    gap: 10px;
    margin-bottom: 10px;
}
.scan-meta small { display: block; color: #8aa3c2; font-size: 10px; letter-spacing: .16em; font-family: Orbitron, sans-serif; }
.scan-meta b { color: #e8f6ff; }
.scan-used code {
    display: block;
    margin-top: 4px;
    color: #b6ff3b;
    word-break: break-all;
    font-size: 12px;
}
.scan-key .ghost-btn { margin-top: 10px; height: 36px; padding: 0 14px; font-size: 10px; width: auto; }
</style>
<?= $this->endSection() ?>
